In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix

In [13]:
import pandas as pd

df = pd.read_csv(r"C:\Users\MERIN\1. hr_analytics.xls")

df

,Age,Gender,Department,MonthlyIncome,TotalWorkingYears,YearsAtCompany,JobSatisfaction,WorkLifeBalance,OverTime,Attrition
0,50,Female,HR,4753,14,8,2,1,Yes,No
1,36,Male,R&D,13123,3,7,3,4,No,No
2,29,Male,HR,19376,16,15,1,3,Yes,No
3,42,Male,HR,9588,19,14,2,4,No,Yes
4,40,Male,R&D,9304,18,8,2,3,No,Yes
...,...,...,...,...,...,...,...,...,...,...
995,34,Female,Sales,7986,2,5,4,3,Yes,Yes
996,51,Female,Sales,4481,26,12,4,2,Yes,No
997,44,Male,HR,6731,27,6,4,1,No,No
998,40,Female,Sales,19835,27,9,1,2,No,No
999,53,Female,HR,13758,15,1,2,4,No,No

In [29]:
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

Number of rows: 1000
Number of columns: 10

In [34]:
print(df.dtypes)

Age                   int64
Gender               object
Department           object
MonthlyIncome         int64
TotalWorkingYears     int64
YearsAtCompany        int64
JobSatisfaction       int64
WorkLifeBalance       int64
OverTime             object
Attrition            object
dtype: object

In [38]:
df.isnull().sum()

Age                  0
Gender               0
Department           0
MonthlyIncome        0
TotalWorkingYears    0
YearsAtCompany       0
JobSatisfaction      0
WorkLifeBalance      0
OverTime             0
Attrition            0
dtype: int64

In [30]:
print(df.isnull().sum())

Age                  0
Gender               0
Department           0
MonthlyIncome        0
TotalWorkingYears    0
YearsAtCompany       0
JobSatisfaction      0
WorkLifeBalance      0
OverTime             0
Attrition            0
dtype: int64

In [39]:
df.duplicated().sum()

np.int64(0)

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Age                1000 non-null   int64
 1   Gender             1000 non-null   object
 2   Department         1000 non-null   object
 3   MonthlyIncome      1000 non-null   int64
 4   TotalWorkingYears  1000 non-null   int64
 5   YearsAtCompany     1000 non-null   int64
 6   JobSatisfaction    1000 non-null   int64
 7   WorkLifeBalance    1000 non-null   int64
 8   OverTime           1000 non-null   object
 9   Attrition          1000 non-null   object
dtypes: int64(6), object(4)
memory usage: 78.3+ KB

In [37]:
df.describe()

,Age,MonthlyIncome,TotalWorkingYears,YearsAtCompany,JobSatisfaction,WorkLifeBalance
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,40.947000,11496.427000,17.518000,10.273000,2.475000,2.463000
std,11.160858,4897.403307,9.585696,5.494967,1.124562,1.101746
min,22.000000,3024.000000,1.000000,1.000000,1.000000,1.000000
25%,31.000000,7240.250000,10.000000,6.000000,1.000000,1.000000
50%,42.000000,11709.000000,17.000000,11.000000,2.000000,2.000000
75%,50.000000,15657.500000,26.000000,15.000000,4.000000,3.000000
max,59.000000,19998.000000,34.000000,19.000000,4.000000,4.000000

In [40]:
total_employees = len(df)
print(f"There are {total_employees} employees in the dataset.")

There are 1000 employees in the dataset.

In [41]:
num_departments = df['Department'].nunique()
print(f"There are {num_departments} departments in the dataset.")

There are 3 departments in the dataset.

In [42]:
all_departments = df['Department'].unique()
print(all_departments)

['HR' 'R&D' 'Sales']

In [43]:
average_age = df['Age'].mean()
print(f"The average employee age is: {average_age:.1f} years old")

The average employee age is: 40.9 years old

In [44]:
min_age = df['Age'].min()
max_age = df['Age'].max()
print(f"Youngest employee age: {min_age} years old")
print(f"Oldest employee age: {max_age} years old")

Youngest employee age: 22 years old
Oldest employee age: 59 years old

In [45]:
gender_counts = df['Gender'].value_counts()
print(gender_counts)

Gender
Male      504
Female    496
Name: count, dtype: int64

In [46]:
department_counts = df['Department'].value_counts()
print(department_counts)

Department
HR       352
Sales    343
R&D      305
Name: count, dtype: int64

In [47]:
(df["TotalWorkingYears"]>10).sum()

np.int64(720)

In [48]:
df.groupby("Department")["MonthlyIncome"].mean()

Department
HR       11604.042614
R&D      11461.272131
Sales    11417.247813
Name: MonthlyIncome, dtype: float64

In [49]:
df[df["Attrition"] == "Yes"].groupby("Department").size()

Department
HR       70
R&D      74
Sales    59
dtype: int64